### ISSUE TITLE
httpoperation.execute() fails if path does not have parameters

### ISSUE THREAD

**Issue by charleswhchan** [Teebytes/TnT-Fuzzer#12]
If an API does not have any parameter (eg. list all objects) the httpoperation.execute() fails:

```
        for parameter in self.op_infos['parameters']:
            # catch path parameters and replace them in url
            if 'path' == parameter['in']:
                url = self.replace_url_parameter(type_definitions, url, parameter['name'], parameter['type'])

            if 'body' == parameter['in']:
                self.request_body = self.create_body(type_definitions, parameter)
                self.request_body = self.fuzz(self.request_body)

            if 'formData' == parameter['in'] or 'query' == parameter['in']:
                type_cls = parameter['type']
                if 'array' == type_cls:
                    type_cls = parameter['items']['type']
                form_data[parameter['name']] = self.create_form_parameter(type_definitions, type_cls)
```
 
https://github.com/Teebytes/TnT-Fuzzer/blob/master/tntfuzzer/httpoperation.py#L33

**Comment by xenobyte** [comment]
Should be solved with pull request #15 but needs review

**Comment by xenobyte** [comment]
@charleswhchan could you checkout the latest version and provide feedback if the bug is solved?

**Comment by charleswhchan** [comment]
Hello @xenobyte, I am still getting a `KeyError: 'parameters'`. 

Perhaps you are missing the following check?
```
if 'parameters' in self.op_infos:
    for parameter in self.op_infos['parameters']:
        ...
```

**Comment by xenobyte** [comment]
Cloud you provide the api specification for this endpoint @charleswhchan ?
